### PR TITLE
issue171-failing-tests-on-Pharo-7

### LINKED ISSUE #171: failing tests on Pharo 7 because of missing Object>>#name
some tests are failing on Pharo 7 because of missing Object>>#name

like PhLCommandContextTest, PhLTreeSelectionTest

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Fix #171: fix a mess in using of #name

### CODE REVIEW

**Comment by guillep** [comment]
Let's wait until tests are run on Pharo 7 too (issue #175)

**Comment by guillep** [comment]
I'll close and re-open this PR so Jenkins takes the new merged commits.

**Comment by guillep** [comment]
There are still a couple of failing tests due to 

```
PhLTreeSelection>>pathNameFor:on:
```

and

```
ByteString(Object)>>doesNotUnderstand: #fullName
PhLVirtualMachineTest>>testCanDetectVMDirectory
```

**Comment by jecisc** [comment]
`ByteString(Object)>>doesNotUnderstand: #fullName` happens in Pharo 7 in other things aswell. 

For example, if you try in Monticello to add filetree or tonel repositories. 

If it's the same bug, it's probably a Pharo bug.

**Comment by VincentBlondeau** [comment]
See https://github.com/pharo-project/pharo-launcher/pull/191

**Pull request closed without merging**
