### PR TITLE
issue169-Remove-dependency-on-Versionner

### PR DESCRIPTION
**Pull request by pavel-krivanek**
Fix issue #169: use commit version for description of Pharo Launcher version

### CODE REVIEW

**Comment by demarey** [comment]
We loose a feature here. For people reporting bugs on the bleeding edge version, we do not get anymore packages versions. Also the version displayed will probably be wrong.
Why not loading the needed versionner package in PL by waiting Cargo?

**Comment by tesonep** [comment]
But moving the development to Github, does not leave the MC version listing obsolete?

**Comment by demarey** [comment]
hum, good catch @tesonep . I though I was awake but maybe not. Indeed, this code does not manage the baseline. So, anyway, it will not work anymore. let's remove it.

**Comment by pavel-krivanek** [comment]
We should modify the loading setup to be fully reproducible. This way the commit version will be enough to describe everything

**Comment by tesonep** [comment]
Maybe open another issue to improve the about message to include the commitish or something like that.

**Comment by demarey** [comment]
done

**Comment by guillep** [comment]
Just `git describe --always` should be enough...

**Pull request merged**
