### PR TITLE
Added exception handling for creating directory in package command

### LINKED ISSUE #640: Image packaging from CLI throws unhandled exception when path targets directory without write permission
**Describe the bug**
Unhandled exception during packaging image

**To Reproduce**
1. Execute e.g. (or directory with no write permission): `./pharo-launcher image package newImage /home/tmp --zip`
2. See error: 
```
PrimitiveFailed: primitive #createDirectory: in UnixStore failed
UnixStore(ProtoObject)>>primitiveFailed:
UnixStore(ProtoObject)>>primitiveFailed
UnixStore(DiskStore)>>createDirectory:
UnixStore(FileSystemStore)>>ensureCreateDirectory:
UnixStore(FileSystemStore)>>ensureCreateDirectory:
FileSystem>>ensureCreateDirectory:
FileReference>>ensureCreateDirectory
PhLImagePackageCliCommand>>createDirectoryForImageToPack
PhLImagePackageCliCommand>>basicExecute
[ self basicExecute ] in PhLImagePackageCliCommand(PhLCliCommand)>>execute in Block: [ self basicExecute ]
FullBlockClosure(BlockClosure)>>on:do:
PhLImagePackageCliCommand(PhLCliCommand)>>execute
PhLImagePackageCliCommand(ClapApplication)>>executeOrPrintHelp
...
```

**Expected behavior**
User-friendly message is shown to user: "Cannot write to target directory <path-specified-in-arg>. Please check write permissions."

**Version information:**
 - OS: Linux/Ubuntu
 - Version: Pharo-launcher CLI prerelease: https://github.com/pharo-project/pharo-launcher/actions/runs/7501196046

**Expected development cost**
Add handing of exception to: `PhLImagePackageCliCommand>>createDirectoryForImageToPack`

### PR DESCRIPTION
**Pull request by Bajger**
- fixes #640

### CODE REVIEW

**Comment by Bajger** [comment]
@demarey I don't know how to write unit test for that, since test class uses memory file system. Not sure if I can inject non-writeable directory (e.g. by using permissions?) and if memory store verifies that.

**Comment by demarey** [comment]
yes, you're right, it is hard to test this. We would need a test on the real file system for this purpose.

**Review by demarey — APPROVED** [review]

**Comment by Bajger** [comment]
@demarey CI is failing, do you have idea why? https://github.com/pharo-project/pharo-launcher/actions/runs/7553602942/job/20565517942#step:6:35

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-launcher">Added exception handling for creating directory in package command · pharo-project/pharo-launcher@826b279</a></strong></div><div>Lets you manage your pharo images and download new ones - Added exception handling for creating directory in package command · pharo-project/pharo-launcher@826b279</div></blockquote>

**Comment by demarey** [comment]
yes, because the test report is not accessible in the job when you are in a PR: https://github.com/pharo-project/pharo-launcher/actions/runs/7553602942/job/20565517942#step:6:35
If you take a look before, you can see all tests are passing :)

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/pharo-project/pharo-launcher">Added exception handling for creating directory in package command · pharo-project/pharo-launcher@826b279</a></strong></div><div>Lets you manage your pharo images and download new ones - Added exception handling for creating directory in package command · pharo-project/pharo-launcher@826b279</div></blockquote>

**Comment by demarey** [comment]
I will need to see how to solve this issue for PRs

**Comment by Bajger** [comment]
Should I merge it? Or wait until test report is accessible for PR?

**Comment by demarey** [comment]
you can merge it

**Pull request merged**
