### PR TITLE
issue194-usage-of-deprecated-Spec-classes

### PR DESCRIPTION
**Pull request by pavel-krivanek**
#194
- new package PharoLauncher-Tests-SpecUI
- remove dependencies on obsolete Spec classes

### CODE REVIEW

**Comment by jecisc** [comment]
Shouldn't you make two PR since it's different issues?

**Comment by pavel-krivanek** [comment]
well, originally I wanted but since it is changing the same file (the baseline), it would produce a conflict. So I tried to attach it to this PR. Reverting

**Comment by jecisc** [comment]
If you don't want to bother with merges I can do it if you wish when one of the PR will be integrated.

**Comment by pavel-krivanek** [comment]
no problem, thanks :-)

**Pull request merged**
