### PR TITLE
[fix] fix recreate image with script

### PR DESCRIPTION
**Pull request by hogoww**
Simple fix with a pair of tests.

### CODE REVIEW

**Comment by hogoww** [comment]
Actually, it needs to add all the configurations in the new file.

**Comment by hogoww** [comment]
I did not copy the full configuration, that's work for another day.
However the script file reference is not carried over to the new image in spite of the fix.
@demarey any Idea what am I missing by any chance?

**Comment by demarey** [comment]
Hi,

Thanks for the PR.
The run of the initialization script is triggered by a flag that is stored in the image metadata: `shouldRunInitializationScript`.
When recreating the image, if the metadata file has not been updated, then the script is not run.
You should use the setter #shouldRunInitializationScript: on a PhlImage to ensure the metadata is flushed.
Metadata file is not deleted when recreating a new image. You should update metadata of the current image before deleting the image.

**Comment by hogoww** [comment]
Thanks a lot for the insight !

**Comment by hogoww** [comment]
I think I did what you told me to, yet, the script is not carried over in the new image.
Anything I am missing?

**Pull request closed without merging**
