### PR TITLE
cleanupLoading

### PR DESCRIPTION
**Pull request by pavel-krivanek**
just upload the version of packages after the Launcher loading. There is a mess around PhLAboutCommand movement - probalby result of some previous merge

### CODE REVIEW

**Comment by guillep** [comment]
@pavel-krivanek is this ok to merge? I cannot understand the implications, but if you say "OK" I press the button :)

**Comment by pavel-krivanek** [comment]
OK ;-)

**Comment by guillep** [comment]
Tx!

**Comment by guillep** [comment]
@pavel-krivanek this broke the repository, we cannot load the PharoLauncher-Spec package because the PhLAboutCommand.class is still there but is not a valid class anymore (see https://github.com/pharo-project/pharo-launcher/tree/development/src/PharoLauncher-Spec.package/PhLAboutCommand.class)

**Pull request merged**
