### PR TITLE
Enhancement/split pharo downloader

### PR DESCRIPTION
**Pull request by VincentBlondeau**

### CODE REVIEW

**Comment by guillep** [comment]
Come on, also commit messages are crappy!

**Comment by VincentBlondeau** [comment]
What I would like is:
- first, reuse what have been done here to download the pharo images. 
- second, avoid as most as possible the dependencies to be able to unload them afterwards. The main issue here is the dependency to the XML and the STON projects.

We should be able to cut these dependencies and put them in another package. Does it seems a good solution for you @guillep ?

**Comment by VincentBlondeau** [comment]
And about commit messages, I am sorry but it is still kinda messy to remove packages from a repo without forgetting a part somewhere...

**Comment by guillep** [comment]
Ok, I've further reviewed this and I fully do not agree without any better explanation. Putting what you call the "Pharo Downloader" in a separate project, and that the launcher depends on that, will just make the launcher more difficult to change... So again, I don't see any benefit on doing this...

> - first, reuse what have been done here to download the pharo images.

Then you depend on the launcher.

> - second, avoid as most as possible the dependencies to be able to unload them afterwards. The main issue here is the dependency to the XML and the STON projects.

This is not a proper justification. I mean, I do not understand WHY this is a problem. There is something else behind and you're not telling it.

You want to save several Kilobytes? You want to deploy Cruiser on a 32kb RAM machine? Really?

- when you work on Java/Scala/Python/Javascript using maven/Sbt/pip/npm, do you tweak the dependencies of all your dependencies? I don't think so. Actually, you don't care too much about the bloat of jars/files you load. And that's because that is really NOT important in general.
- Do you manually unload Pharo packages that you don't use too? I don't think that you do.

Or the problem is about dependency conflicts?

Also, are those KB worth the effort of splitting everything? I'm not sure you're taking into account the associated cost: 
 - more projects to version
 - more dependencies to manage
 - more repositories to know

And only to avoid loading XML? If you want to minimize dependencies, you can just use Zinc and avoid EVERY dependency.
```
ZnClient new
	url: self defaultUrl;
	signalProgress: true;
	downloadTo: self defaultDownloadFilename
```

**Comment by guillep** [comment]
@VincentBlondeau ? I'll close it for now

**Pull request closed without merging**
