### PR TITLE
speedup-reading-of-files-metadata

### PR DESCRIPTION
**Pull request by jecisc**
Speed up ston reading.

Building the list of images tool 2.5sec before in my case. It now takes 200ms.

### CODE REVIEW

**Comment by demarey** [comment]
thanks!

**Comment by svenvc** [comment]
Very good!

**Comment by jecisc** [comment]
@svenvc I was wondering. Maybe Ston could cache the list of all subclasses of #Object and register to the "class added" event to discard the cache?

But maybe I am thinking this too much. In general, we read one big file and not a lot of small ones.

**Comment by svenvc** [comment]
What you did is the way it was designed: cache and reuse the reader instance.

A global cache needs too much maintenance.

**Pull request merged**
